# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ae911d653b9fed0b8547a984a7607904f725285e6afaa0fb8726bd343306fc73f4df5d316caf03fb98a6fd6f0943469af2fd95e80c235d962722037548720f

test:
  secret_key_base: 00b18a61354792eabd672125ea80e5d88e8e336496192bce873b8f09f2b3862debbcb3ab1fb650ad5495afdaba6a5a39572391b1c59a74baf0296293d336ae56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
